### PR TITLE
Junit5

### PR DESCRIPTION
**Pull request by stbischof**
Junit5 on base of
Apache Felix Eclipse Formatter Template

### CODE REVIEW

**Comment by stbischof** [comment]
will rebase after formatting

**Comment by tjwatson** [comment]
OK, you can rebase now.  Thanks.

**Comment by tjwatson** [comment]
With your changes locally I don't see the tests get executed.  Only see results like this:
```
[INFO] Running org.atomos.framework.AtomosRuntimeTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.atomos.framework.AtomosRuntimeTest
```

**Comment by stbischof** [comment]
My fault. Sorry. Used default eclipse formatter template after Importing the Felix Template

**Comment by tjwatson** [comment]
I squashed the three commits to avoid the noise of the format changes back and forth.  This is now merged.

Thanks!

**Pull request merged**
