### PR TITLE
WIP: Mojo

### PR DESCRIPTION
**Pull request by stbischof**
#15

### CODE REVIEW

**Comment by tjwatson** [comment]
Is the intention to start having the maven plugins/tools for substrate to exist under the atomos.substrate module?

**Comment by stbischof** [comment]
yes, but i am not sure, that all maven plugins will only handle substrate. 
* substrate.common
* substrate.osgi-runtim-config (config)
* substrate.maven-plugin

**Comment by tjwatson** [comment]
> What is the best way to speak with you about such small questions? Issues like #25?

Lets try gitter.  I just tried creating a new community at https://gitter.im/Atomos-OSGi-Connect-Framework/community

**Comment by tjwatson** [comment]
Hi Stefan, since I see you working on this PR.  I wanted to point you to some gitter questions I asked you.  Can you have a look and respond?  Thanks.

**Pull request closed without merging**
